FROM python:3.11-slim

WORKDIR /app

COPY ./requirements.txt /app/
COPY ./requirements-dev.txt /app/

RUN pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir -r requirements-dev.txt

COPY ./storeapi /app/storeapi/
COPY ./storeapi/food_vision_model/food_vision_model.onnx /app/storeapi/food_vision_model/

ENV ENV_STATE=test

CMD ["python", "-m", "pytest", "/app/storeapi/tests"]
