FROM python:3.11-slim

WORKDIR /app

COPY ./requirements.txt /app/
COPY ./requirements-dev.txt /app/

RUN pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir -r requirements-dev.txt

COPY ./foodapp /app/foodapp/
COPY ./foodapp/integrations/vision/food_vision_model.onnx /app/foodapp/integrations/vision/
COPY ./tests /app/tests

ENV ENV_STATE=test

CMD ["python", "-m", "pytest", "/app/tests"]
